id = "visual-assist-dark"
name = "Visual Assist Dark Theme"
version = "0.0.3"
schema_version = 1
authors = ["Andy Duplain <trojanfoe@gmail.com>"]
description = "Visual Assist Dark Theme"
repository = "https://github.com/trojanfoe/visual_assist_dark.zed"
